<?php

/**
 * @file
 * Code for controlling purge.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_cron().
 */
function purge_control_cron() {
  // Adds a recovery mechanism to automatically enable purging in case of
  // failures.
  \Drupal::service('purge_control.purge_control')->autoEnablePurge();
}

/**
 * Implements hook_help().
 */
function purge_control_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the purge_ajax_processor module.
    case 'help.page.purge_control':
      $output = '<pre>' . file_get_contents(drupal_get_path('module', 'purge_control') . '/README.md') . '</pre>';
      return $output;

    default:
  }
}
